# ===============================
# CONFIGURAÇÃO DO SERVIDOR
# ===============================

server.port=${PORT:8080}

# ===============================
# CONFIGURAÇÃO DO MYSQL (Aiven)
# ===============================

spring.datasource.url=jdbc:mysql://mysql-1ef341fd-gym-8manager.b.aivencloud.com:23091/defaultdb?sslMode=REQUIRED

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect